name: Release debug APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to create release (e.g. v0.9.0-beta2)'
        required: true
        default: 'v0.9.0-beta2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Ensure local.properties (Android SDK path)
        run: |
          if [ -d "android" ]; then
            echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          else
            echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          fi

      # Gradle Wrapperが無くてもOK。指定バージョンのGradleでビルドします
      - name: Build debug APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug
          gradle-version: 8.7
          build-root-directory: android

      - name: Collect APK and SHA-256
        run: |
          APK=$(find . -path "*/outputs/apk/debug/*.apk" -name "*.apk" | head -n 1)
          echo "Found APK: $APK"
          mkdir -p artifacts
          cp "$APK" artifacts/app-debug.apk
          sha256sum artifacts/app-debug.apk | tee artifacts/SHA256.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
          name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
          prerelease: true
          files: |
            artifacts/app-debug.apk
            artifacts/SHA256.txt
