name: Release debug APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Ensure local.properties
        run: |
          if [ -d "android" ]; then
            echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          else
            echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          fi

      - name: Build debug APK (auto-detect wrapper)
        run: |
          set -e
          if [ -f "./android/gradlew" ]; then
            chmod +x ./android/gradlew
            cd android
            ./gradlew assembleDebug
          elif [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew assembleDebug
          else
            echo "::error::Gradle wrapper (gradlew) が見つかりません。android/ または リポジトリ直下に gradlew, gradlew.bat, gradle/wrapper/* をコミットしてください。"
            exit 1
          fi

      - name: Collect artifacts and SHA-256
        run: |
          APK=$(find . -path "*/outputs/apk/debug/*.apk" -name "*.apk" | head -n 1)
          echo "Found APK: $APK"
          mkdir -p artifacts
          cp "$APK" artifacts/app-debug.apk
          sha256sum artifacts/app-debug.apk | tee artifacts/SHA256.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/app-debug.apk
            artifacts/SHA256.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
